### ISSUE TITLE
Docker on Synology NAS fixing group permissions to access mounted volume 

### ISSUE THREAD

**Issue by jxsl13** [bernmic/ocrmypdf-watchdog#3]
```yml
ocrmypdf-watchdog-alexander:
    container_name: OCRmyPDF-alexander
    network_mode: none
    image: darthbermel/ocrmypdf-watchdog:latest
    user: ":100"     # <--- added this line here
    environment:
      OCRMYPDF_IN: /in
      OCRMYPDF_OUT: /out
      WATCHDOG_FREQUENCY: 5
      WATCHDOG_EXTENSIONS: pdf,jpg,jpeg,tif,tiff,png,gif
      OCRMYPDF_BINARY: ocrmypdf
      OCRMYPDF_PARAMETER: -l eng+deu --rotate-pages --deskew --jobs 4 --output-type pdfa
    volumes:
    - /volume1/Scans/alexander:/in
    - /volume1/homes/alexander/Drive/Scans:/out:rw
    restart: unless-stopped

```
